# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Finpass < Formula
  desc "finpass generates passwords using Finnish language words"
  homepage "https://github.com/hermo/finpass"
  version "1.4.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hermo/finpass/releases/download/v1.4.1/finpass_1.4.1_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "0684d044312d98f303b32b0f8081700e19895bf2cf442596476884644a68895a"

      def install
        bin.install "finpass"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hermo/finpass/releases/download/v1.4.1/finpass_1.4.1_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "c6bcc742d6a69b2f8dcacbfce1068cf4987d6473b83713365646021cecc2dd71"

      def install
        bin.install "finpass"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/hermo/finpass/releases/download/v1.4.1/finpass_1.4.1_linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "e0f9abf5d3f415dc4195e1fd61b0fa665c2e72e7d3f3d02267ee6ce3ff99b6fd"
      def install
        bin.install "finpass"
      end
    end
  end
end
