# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Finpass < Formula
  desc "finpass generates passwords using Finnish language words"
  homepage "https://github.com/hermo/finpass"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/hermo/finpass/releases/download/v1.0.0/finpass_1.0.0_macOS_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "9d6da9a0555bc453162dd596e6b9fc004e6a90740db06e87fa5b524657a9a14d"

      def install
        bin.install "finpass"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/hermo/finpass/releases/download/v1.0.0/finpass_1.0.0_macOS_amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "c5c844f61274269d66cad94c93c7a15b2a73b12a5115bc9492090cbc9fef1f3c"

      def install
        bin.install "finpass"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/hermo/finpass/releases/download/v1.0.0/finpass_1.0.0_linux_amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "b4389996e72a6192a97fb6ad1589cc8a3ac3918992fb156966384239d568dfd1"

      def install
        bin.install "finpass"
      end
    end
  end
end
