# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Finpass < Formula
  desc "finpass generates passphrases using Finnish language words"
  homepage "https://github.com/hermo/finpass"
  version "1.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hermo/finpass/releases/download/v1.5.0/finpass_1.5.0_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "ba7e49bd1f8cbf945dfe9f894c900c5dfbecc59f2e1d501c205183804788cade"

      def install
        bin.install "finpass"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hermo/finpass/releases/download/v1.5.0/finpass_1.5.0_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "ab384c3e5a540be8a08e5ca49ac47bf5ef616b4d7d1dc50ac4db888b105ed64a"

      def install
        bin.install "finpass"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/hermo/finpass/releases/download/v1.5.0/finpass_1.5.0_linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "70bfa32038c7dd48692ef0c4800d4605003456e25e0d84ed8eb45e763fd1efcd"
      def install
        bin.install "finpass"
      end
    end
  end
end
